sonar.projectKey=backend
sonar.sources=.
sonar.exclusions=test_*.py
sonar.python.version=3.11
sonar.host.url=http://sonarqube:9000
sonar.python.xunit.reportPath=test-results/pytest-report.xml
sonar.python.coverage.reportPaths=test-results/coverage.xml
